services:
  mais-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mais-api

  mais-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis-stack}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REMOTION_APP_FUNCTION_NAME=${REMOTION_APP_FUNCTION_NAME}
      - REMOTION_APP_SERVE_URL=${REMOTION_APP_SERVE_URL}
    ports:
      - "8000:8000"
    # depends_on:
    #   - redis-stack
    #   - mais-worker

  mais-worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis-stack}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - API_HOST=${API_HOST:-mais-api}
      - API_PORT=${API_PORT:-8000}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
