version: '3.8'

services:
  mais-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mais-be

  mais-be:
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
      - redis-queue

  redis-queue:
    image: "giacomocortesi/redis-queue:latest"
    environment:
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server

  redis-server:
    image: "redis:latest"
