version: '3.8'

services:
  mais-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mais-be

  mais-be:
    build:
      context: ./be
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis-stack

  mais:
    build:
      context: ./mais
      dockerfile: Dockerfile
    depends_on:
      - redis-stack
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - API_URL=http://mais-be:8080

  redis-stack:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
