# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-01-19T16:25:28+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

class JobInfo(BaseModel):
    config: Optional[JobConfig] = None
    filename: Optional[str] = Field(None, title='filename')

class JobRequest(BaseModel):
    id: Optional[str] = Field(None, title='id')
    info: Optional[JobInfo] = None

class JobResponse(BaseModel):
    id: str = Field(..., title='id')
    info: JobInfo = None
    status: Status = Field(..., title='status')
    data: Optional[TranscriptionData] = Field(None, title='id')

class JobConfig(BaseModel):
    model_size: str = Field(..., title='model_size')
    subtitles_frequency: int = Field(..., title='subtitles_frequency')
    language: str = Field(..., title='language')
    speaker_detection: bool = Field(..., title='speaker_detection')

class Status(str, Enum):
    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class Word(BaseModel):
    word: str = Field("", title='word')
    start: float = Field(..., title='start')
    end: float = Field(..., title='end')
    score: float = Field(..., title='score')


class Segment(BaseModel):
    start: float = Field(..., title='start')
    end: float = Field(..., title='end')
    text: str = Field(..., title='text')
    words: Optional[List[Word]] = Field(None, title='words')


class TranscriptionData(BaseModel):
    segments: List[Segment] = Field(..., title='segments')
    word_segments: Optional[List[Word]] = Field(None, title='word_segments')
    language: Optional[str] = Field(None, title='language')


class FileResponse(BaseModel):
    id: Optional[str] = Field(None, title='id')
    filename: Optional[str] = Field(None, title='filename')
    upload_date: Optional[datetime] = Field(None, title='upload_date')
    video_url: Optional[str] = Field(None, title='video_url')
    image_url: Optional[str] = Field(None, title='image_url')


class ErrorModel(BaseModel):
    title: Optional[str] = Field(None, title='title')
    detail: Optional[str] = Field(None, title='detail')
    status: Optional[int] = Field(None, title='status')
    type: Optional[str] = Field(None, title='type')


class FieldTranscriptionIdPatchRequest(BaseModel):
    data: Optional[TranscriptionData] = None


class FieldFilePostRequest(BaseModel):
    file: Optional[bytes] = None


class TranscriptionRequest(BaseModel):
    id: Optional[str] = Field(None, title='id')
    data: TranscriptionData = None
    job_id: Optional[str] = Field(None, title='job_id')
    filename: Optional[str] = Field(None, title='filename')
    
class TranscriptionResponse(BaseModel):
    id: str = Field(None, title='id')
    data: TranscriptionData = None
    job_id: str = Field(None, title='job_id')
    filename: str = Field(None, title='filename')
    original_data: TranscriptionData


class FieldTranscriptionPostRequest(BaseModel):
    schema_: Optional[TranscriptionRequest] = Field(None, alias='schema')
